server:
  port: 8083

azure:
  cosmosdb:
    uri:
    key:
    database:

spring:
  jms:
    servicebus:
      connection-string:
#      idle-timeout:
#      pricing-tier:
      queues:
        queue-1:




